version: "3.8"

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: shikireki-mongodb-development
    restart: always
    networks:
      - shikireki-network-development
    volumes:
      - shikireki-volume-development:/data/db
    environment:
      MONGODB_DATABASE: shikireki
    env_file:
      - ./configs/.env.development
    ports:
      - "27017:27017"

  mongodb-express:
      image: mongo-express:latest
      container_name: shikireki-express-development
      restart: always
      networks:
        - shikireki-network-development
      volumes:
        - shikireki-volume-development:/data/db
      environment:
        ME_CONFIG_MONGODB_SERVER: shikireki-mongodb-development
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_AUTH_USERNAME: root
        ME_CONFIG_MONGODB_AUTH_PASSWORD: gkkI7ifm3cmOpQerxb
        ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      env_file:
        - ./configs/.env.development
      depends_on:
        - mongodb
      ports:
        - "4082:8081"

volumes:
  shikireki-volume-development:
    name: shikireki-volume-development
    driver: local
networks:
  shikireki-network-development:
    name: shikireki-network-development
    driver: bridge
